[package]
name = "timing-attack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.4"
rand = "0.8.5"

[[bench]]
name = "timing_bench_array"
harness = false